[build]
  install = "pip install -r requirements.txt"
  start = "gunicorn breakspace_backend.wsgi --log-file -"

[deploy]
  release = "python manage.py migrate"
  populate_db = "python manage.py populate_d"
